"""
Critic module for evaluating proposed execution plans.
Ensures safety, logic, and adherence to rules before execution.
"""
# pylint: disable=broad-exception-caught, too-few-public-methods
import asyncio
import json
from typing import Tuple

import ollama

from core.logger import setup_logger

logger = setup_logger("Critic")


class Critic:
    """
    Evaluates the JSON plans generated by the Planner.
    """
    def __init__(self, model_name: str) -> None:
        self.model_name = model_name

    async def verify_plan(self, user_task: str, plan_json: str) -> Tuple[bool, str]:
        """
        Evaluates a proposed JSON plan against the user's task.
        Ensures the plan makes logical sense and contains no inherently dangerous steps.
        Returns (approved: bool, feedback: str)
        """
        system_prompt = """
        You are the Critic Agent for an OS automation system. 
        Your job is to review a proposed JSON execution plan generated by a Planner Agent to fulfill a User Task.

        RULES:
        1. Ensure the plan logically accomplishes the user's request.
        2. Reject plans that use dangerous commands (e.g., formatting disks, deleting system files, fork bombs).
        3. Reject plans that seem to hallucinate steps unrelated to the goal.
        4. If the plan is good, set "approved" to true.
        5. If the plan is bad, set "approved" to false and provide specific "feedback" detailing what is wrong so the Planner can fix it.

        OUTPUT FORMAT:
        You must output ONLY valid JSON in this exact format.
        {
            "approved": true | false,
            "feedback": "Your critique here."
        }
        """

        user_prompt = f"USER TASK: {user_task}\n\nPROPOSED PLAN:\n{plan_json}"

        try:
            logger.debug("Asking Critic (%s) to evaluate the plan...", self.model_name)
            
            response = await asyncio.to_thread(
                ollama.chat,
                model=self.model_name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                format='json'
            )
            content = response.get('message', {}).get('content', '').strip()

            try:
                result = json.loads(content)
                is_approved = result.get('approved', False)
                feedback = result.get('feedback', 'No feedback provided.')

                if is_approved:
                    logger.info("Critic approved the plan!")
                else:
                    logger.warning("Critic REJECTED the plan: %s", feedback)

                return is_approved, feedback
            except json.JSONDecodeError:
                logger.error("Critic output invalid JSON: %s", content)
                return False, f"Critic failed to output valid JSON: {content}"

        except Exception as e:
            logger.error("Critic evaluation failed: %s", e)
            return False, f"Critic encountered an error: {e}"
