"""
Executor module to carry out the CLI, GUI, and Browser commands generated by the Planner.
"""
# pylint: disable=broad-exception-caught, too-many-return-statements, line-too-long
import asyncio
import traceback
from typing import Any, Dict, Optional, Tuple

from core.logger import setup_logger

logger = setup_logger("Executor")


class Executor:
    """
    Executes the planned steps securely using native tools or GUI automation.
    """
    def __init__(self, ui_parser: Any = None) -> None:
        self.ui_parser = ui_parser

        # Lazy load browser variables
        self._pw: Any = None
        self._browser: Any = None
        self._page: Any = None

    def _get_browser_path(self, browser_name: str) -> Optional[str]:
        """Dynamically finds the browser executable path via Windows Registry."""
        import winreg # pylint: disable=import-outside-toplevel
        for hive in [winreg.HKEY_LOCAL_MACHINE, winreg.HKEY_CURRENT_USER]:
            try:
                key = winreg.OpenKey(
                    hive, rf"SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\{browser_name}.exe")
                path, _ = winreg.QueryValueEx(key, "")
                return str(path)
            except Exception:
                continue
        return None

    async def _init_browser(self) -> None:
        if not self._pw:
            try:
                from playwright.async_api import async_playwright # pylint: disable=import-outside-toplevel
                self._pw = await async_playwright().start()
                import os # pylint: disable=import-outside-toplevel

                # Define the local browser profile directory
                profile_dir = os.path.join(os.getcwd(), "browser_profile")
                if not os.path.exists(profile_dir):
                    os.makedirs(profile_dir)

                brave_path = self._get_browser_path("brave")
                if brave_path and os.path.exists(brave_path):
                    logger.info("Launching Brave Browser with Persistent Context...")
                    self._browser = await self._pw.chromium.launch_persistent_context(
                        user_data_dir=profile_dir,
                        headless=False,
                        executable_path=brave_path,
                        no_viewport=True
                    )
                else:
                    logger.info("Brave not found. Launching default Chromium with Persistent Context...")
                    self._browser = await self._pw.chromium.launch_persistent_context(
                        user_data_dir=profile_dir,
                        headless=False,
                        no_viewport=True
                    )

                # launch_persistent_context returns a BrowserContext which usually has 1 page by default
                if self._browser.pages:
                    self._page = self._browser.pages[0]
                else:
                    self._page = await self._browser.new_page()
            except Exception as e:
                logger.error("Failed to initialize browser: %s", e)
                raise

    async def shutdown(self) -> None:
        """Shuts down browser and other persistent services."""
        try:
            if self._browser:
                await self._browser.close()
            if self._pw:
                await self._pw.stop()
            logger.debug("Browser shutdown successful.")
        except Exception as e:
            logger.error("Error during browser shutdown: %s", e)

    async def execute_step(self, step: Dict[str, Any]) -> Tuple[bool, str]:
        """
        Executes a single planned step.
        Returns (success: bool, output/message: str)
        """
        method = step.get('method')
        action = str(step.get('action'))
        target = str(step.get('target', ''))

        try:
            # Smart fallback for LLM hallucination:
            # Auto-correct "action": "browser" and "target": "goto ..."
            if action == "browser" and str(target).startswith("goto "):
                action = "goto"
                target = str(target).replace("goto ", "", 1).strip()
                method = "browser"
                
            # Force the correct execution pipeline based on the action.
            if action == "run_command":
                method = "cli"
            elif action in ["goto", "click_dom", "type_dom"]:
                method = "browser"
            elif action in ["click", "type", "hotkey", "search_start_menu"]:
                method = "gui"
            elif action in ["sleep", "close_browser", "open_app"]:
                method = "system"

            logger.debug("Executing step - Action: %s, Target: %s, Method: %s", action, target, method)

            if method == "cli":
                return await self._execute_cli(target)
            if method == "gui":
                return await self._execute_gui(action, target)
            if method == "browser":
                return await self._execute_browser(action, target)
            if method == "system":
                if action == "sleep":
                    logger.info("System sleeping for %s seconds...", target)
                    await asyncio.sleep(float(target))
                    return True, f"Slept for {target} seconds."
                if action == "close_browser":
                    logger.info("Closing browser...")
                    await self.shutdown()
                    return True, "Closed the browser."
                if action == "open_app":
                    logger.info("Opening application: %s...", target)
                    return await self._execute_cli(f"Start-Process {target}")
                
                error_msg = f"Unknown system action: {action}"
                logger.warning(error_msg)
                return False, error_msg

            error_msg = f"Unknown execution method: {method}"
            logger.warning(error_msg)
            return False, error_msg

        except Exception:
            err_msg = traceback.format_exc()
            logger.error("Exception during execution: %s", err_msg)
            return False, f"Exception during execution:\n{err_msg}"

    async def _execute_cli(self, command: str) -> Tuple[bool, str]:
        """Executes a native command via subprocess."""
        try:
            import base64 # pylint: disable=import-outside-toplevel
            logger.debug("Running CLI command: %s", command)
            # Encode the command as Base64 UTF-16LE to avoid quoting issues
            encoded = base64.b64encode(
                command.encode('utf-16-le')).decode('ascii')
            process = await asyncio.create_subprocess_shell(
                f"powershell -EncodedCommand {encoded}",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE
            )
            try:
                # Add a 60-second timeout to prevent infinite hangs
                stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=60.0)
            except asyncio.TimeoutError:
                process.kill()
                # Ensure the process is fully terminated
                await process.wait()
                logger.error("CLI command timed out after 60 seconds: %s", command)
                return False, "Command failed: Timed out after 60 seconds."

            output = stdout.decode().strip()
            error_output = stderr.decode().strip()

            # Clean up PowerShell's ugly CLIXML error formatting
            if "#< CLIXML" in error_output:
                import re # pylint: disable=import-outside-toplevel
                matches = re.findall(r'<S S="Error">([^<]+)</S>', error_output)
                if matches:
                    error_output = "".join(matches).replace("_x000D__x000A_", "\n").strip()
                else:
                    error_output = "PowerShell error occurred (CLIXML)."

            if process.returncode == 0:
                logger.debug("CLI command succeeded: %s", output)
                return True, output if output else "Command executed successfully with no output."

            logger.error("CLI command failed (%s): %s", process.returncode, error_output)
            return False, f"Command failed with code {process.returncode}: {error_output}"

        except Exception as e:
            logger.error("Failed to launch subprocess: %s", e)
            return False, f"Failed to launch subprocess: {str(e)}"

    async def _execute_gui(self, action: str, target: str) -> Tuple[bool, str]:
        """
        Executes a GUI action.
        This relies on the UI Parser to find coordinates, then pyautogui to act.
        """
        try:
            import pyautogui # pylint: disable=import-outside-toplevel
            pyautogui.FAILSAFE = True

            if action == "type":
                logger.info("Vision Typing: '%s'", target)
                pyautogui.write(target, interval=0.05)
                pyautogui.press('enter')
                return True, f"Typed '{target}' and pressed enter."

            if action == "hotkey":
                logger.info("Vision Hotkey: '%s'", target)
                keys = target.split('+')
                pyautogui.hotkey(*keys)
                return True, f"Pressed hotkey {target}."

            if action == "search_start_menu":
                logger.info("Vision Start Menu Search: '%s'", target)
                pyautogui.press('win')
                await asyncio.sleep(1.0)
                pyautogui.write(target, interval=0.05)
                await asyncio.sleep(1.0)
                pyautogui.press('enter')
                return True, f"Searched Start Menu for '{target}' and pressed enter."

            if not self.ui_parser:
                return False, "UI Parser not initialized for coordinate finding."

            coords = self.ui_parser.find_element(target)
            if not coords:
                if action == "click" and "start" in target.lower():
                    logger.info("Falling back to Windows key for Start button.")
                    pyautogui.press('win')
                    return True, "Pressed Windows key as fallback for Start button."
                logger.warning("Could not find element '%s' on screen.", target)
                return False, f"Could not find element '{target}' on screen."

            x, y = coords

            if action == "click":
                logger.info("Vision Click at (%s, %s) for '%s'", x, y, target)
                pyautogui.moveTo(x, y, duration=0.5)
                pyautogui.click()
                return True, f"Clicked on '{target}' at ({x}, {y})."

            logger.warning("Unsupported GUI action: %s", action)
            return False, f"Unsupported GUI action: {action}"

        except Exception as e:
            logger.error("GUI Execution Error: %s", e)
            return False, f"GUI Error: {e}"

    async def _execute_browser(
            self, action: str, target: str, retry: bool = True) -> Tuple[bool, str]:
        """
        Executes a browser action directly in the DOM using Playwright.
        """
        try:
            await self._init_browser()

            if not self._page:
                return False, "Browser page not initialized."

            if action == "goto":
                if not target:
                    target = "https://google.com"
                # Proactive Fix: Auto-prepend https:// if the LLM forgets the protocol
                if not target.startswith("http"):
                    target = "https://" + target
                    
                logger.info("Browser Navigating: %s", target)
                try:
                    await self._page.goto(target, wait_until="load")
                    return True, f"Navigated to {target}."
                except Exception as e:
                    if "ERR_NAME_NOT_RESOLVED" in str(e) or "ERR_CONNECTION_REFUSED" in str(e):
                        logger.warning("Domain not resolved. Falling back to DuckDuckGo Search...")
                        # Extract the base query from the URL to search it instead
                        search_query = target.replace('https://', '').replace('http://', '').replace('/', ' ')
                        search_url = f"https://duckduckgo.com/?q={search_query}"
                        await self._page.goto(search_url, wait_until="load")
                        return True, f"Could not resolve {target}. Executed a DuckDuckGo search instead."
                    raise e

            if action == "click_dom":
                logger.info("Browser Click DOM: '%s'", target)
                await self._page.click(target)
                return True, f"Clicked element matching '{target}'."

            if action == "type_dom":
                if ":::" not in target:
                    return False, "Target for type_dom must be in format 'selector:::text'."
                selector, text = target.split(":::", 1)
                logger.info("Browser Type DOM: '%s' into '%s'", text, selector)
                await self._page.fill(selector, text)
                return True, f"Typed text into '{selector}'."

            logger.warning("Unsupported browser action: %s", action)
            return False, f"Unsupported browser action: {action}"

        except Exception as e:
            err_str = str(e)
            logger.error("Browser execution failed: %s", err_str)
            if retry and (
                    "Connection closed" in err_str or "Target closed" in err_str or "has been closed" in err_str):
                logger.warning("Connection dead. Restarting Playwright instance...")
                await self.shutdown()
                self._pw = None
                self._browser = None
                self._page = None
                return await self._execute_browser(action, target, retry=False)
            return False, f"Browser execution failed: {err_str}"
